# Site settings
title: 🇺🇦 Українські конференції з кібер-безпеки
description: Анонси, програми та архів матеріалів українських подій з кібер-безпеки.
lang: uk

# Build settings
markdown: kramdown
theme: jekyll-theme-primer
